StarRocks/docs.zh-cn

sql-reference/sql-statements/data-definition/DROP DATABASE.md
fix error in drop database force method @imay
=> fix the error in drop database force

sql-reference/sql-statements/data-definition/DROP TABLE.md
drop table error fix @imay @decster
=> fix error in drop table

quick_start/Deploy.md
update SHOW PROC and drop backends grammar mistakes
=> update SHOW PROC and drop backends

sql-reference/sql-statements/data-definition/CREATE TABLE.md
=> Update CREATE TABLE.md

using_starrocks/Lateral_join.md
=> Update lateral join

release_notes/release-1.19.md
update release notes with 1.19.1
=> update release notes with 1.19.1

quick_start/Test_faq.md
=> Correct the link address of profile

administration/Query_management.md
=> Update Query_management.md 

loading/BrokerLoad.md
exec_mem_limit is invalid property. load_mem_limit is the correct.
=> [DOC] Update BrokerLoad.md

table_design/Materialized_view.md
update materialized view in table design
=> update materialized view in table design

TOC.md
=> Add the "split" directory

loading/Flink-connector-starrocks.md
=> update some links

sql-reference/sql-statements/data-types/DECIMAL.md
1.19.0新增了对decimal的默认值的设置，增加相关描述
=> Add a description of the differences between different versions of "Decimal"

loading/Loading_intro.md
Update the link of Streamload demo
=> Update the link of Streamload demo

TOC.md
Remove the empty line in the TOC.md
=> Remove the empty line in the TOC.md

loading/Flink-connector-starrocks.md
update the smt link to official download site, so we don't need to update it any more
=> update the smt link

sql-reference/sql-statements/account-management/ALTER USER.md
=> Update ALTER USER.md

using_starrocks/Colocation_join.md
and  remove unused config.
https://github.com/StarRocks/starrocks/pull/2218
=> Refactor colocate group status modification api

administration/Configuration.md
=> FE配置项priority_networks描述错误

sql-reference/sql-statements/data-definition/ALTER TABLE.md
Update the syntax of  delete table partition  part
=> Update ALTER TABLE.md

sql-reference/sql-statements/data-definition/DROP DATABASE.md
=> Update DROP DATABASE.md

using_starrocks/External_table.md
update 2.1 feature (external table based on a CSV file)
=> sr2.1_external table based on a CSV file

sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT
=> sr2.1_ctas

table_design/Data_model.md, using_starrocks/External_table.md
=> 2.1_fixbrokenlinks

administration/Profiling.md, table_design/Data_distribution.md
=> Fix Spelling mistakes

TOC.md
=> update toc.md add release_2.0 (#197)

loading/PrimaryKeyLoad.md
Update PrimaryKeyLoad.md format
=> Update PrimaryKeyLoad.md format

sql-reference/sql-functions/aggregate-functions/retention.md
Add doc for aggregate function of retention.
=> Add Doc for retention

sql-reference/sql-statements/data-definition/CREATE TABLE AS SELECT.md
fixed incorrect function name and number:
- the function name should be CTAS.
- the number of tables is 4 because there are 4 tables
=> Update CREATE TABLE AS SELECT.md

sql-reference/sql-statements/data-types/VARCHAR.md
=> Fix VARCHAR Range in Code comment

release_notes/release-2.0.md
* add 2.0.4 release note
* Update release-2.0.md
=> add 2.0.4 release note (#431)

.github/workflows/buildcheck.yml
add npm run build check action to prevent docs-site build unsuccessful
=> add buildcheck.yml

TOC.md, sql-reference/sql-statements/Administration/CREATE RESOURCE GROUP.md
- Add resource group to sql stat
- modify TOC
=> Add resource group to sql stat

administration/Memory_management.md
Related PR: https://github.com/StarRocks/starrocks/pull/6400.
=> Add session variable query_mem_limit

sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md
=> Update ROUTINE LOAD.md

sql-reference/sql-functions/math-functions/rand.md
revise rand () according to jira issue
=> Update rand ()

using_starrocks/JAVA_UDF.md
=> Fix Wrong function name in JAVA_UDF.md

using_starrocks/JAVA_UDF.md
=> Esoragoto spirit patch 2

faq/Others.md, using_starrocks/timezone.md
doc walkthrough: the following two docs are finished and ready to be updated to the doc center.
时区
其他（faq里面的）
=> update two docs

faq/Others.md, faq/loading/Spark_load_faq.md, using_starrocks/External_table.md, using_starrocks/timezone.md
1. resolve one github issue (external table)
2. delete two empty faq docs
3. duplicate two docs that are revised and released to the main branch before(timezone nad other faq)
=> doc changes

sql-reference/sql-statements/data-definition/CREATE TABLE.md, sql-reference/sql-statements/data-definition/HLL.md
https://starrocks.atlassian.net/browse/SR-9774
=> resolve one jira issue

TOC.md, quick_start/Create_table.md, sql-reference/sql-functions/percentile-functions/percentile_approx_raw.md, sql-reference/sql-statements/data-definition/CREATE TABLE.md
=> fix bugs in percentile topic title and _desc

sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
=> stream load

administration/Configuration.md
Fixes #907 
Signed-off-by: xiaoyong-z <a997647204@gmail.com>
=> Update compaction configuration

loading/PrimaryKeyLoad.md, sql-reference/sql-statements/data-manipulation/DELETE.md
Reverts StarRocks/docs.zh-cn#912
=> Revert "Update DELETE and loading into Primary Key tables"

TOC.md
Reverts StarRocks/docs.zh-cn#900
=> Revert "Update TOC.md"

sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
=> Update STREAM LOAD.md

administration/Configuration.md
This PR adds description for `empty_load_as_error` in fe.conf
=> feat: add empty_load_as_error

sql-reference/sql-statements/Administration/ALTER SYSTEM.md, sql-reference/sql-statements/data-definition/CREATE REPOSITORY.md, sql-reference/sql-statements/data-definition/DROP REPOSITORY.md
=> Modify some REPOSITORY Example

quick_start/Create_table.md
=>  Add required field note

administration/Query_management.md
=> Walkthrough: Query Management

sql-reference/sql-statements/account-management/SET PROPERTY.md
=> Update SET PROPERTY.md

administration/Authentication.md
=> Elaborate Create User

administration/Cluster_administration.md, sql-reference/sql-statements/Administration/CREATE RESOURCE GROUP.md, unloading/Flink_connector.md
Fixes #   
Changes proposed in this pull request: remove spaces from <>
=> fix spaces in <>

loading/Flink-connector-starrocks.md
=> update the document content

sql-reference/sql-statements/data-definition/CREATE TABLE.md
修改语法中的错别字, ENGINE增加iceberg及hudi, 修正字段NULL|NOT NULL的说明
=> 修改语法中的错别字, ENGINE增加iceberg及hudi, 修改字段NULL|NOT NULL的说明

administration/Metadata_recovery.md, loading/Flink_cdc_load.md, using_starrocks/Using_bitmap.md
=> Fix ANCHOR

loading/BrokerLoad.md
Fixes #   
Changes proposed in this pull request:
-
-
-
@EsoragotoSpirit
=> add flowchart to broker load v2.2

administration/Configuration.md
`enable_collect_query_detail_info`配置的解释应该是”是否xxxx“
=> enable_collect_query_detail_info配置应该解释为”是否xxxx“

sql-reference/sql-statements/data-definition/CREATE MATERIALIZED VIEW.md
”CREATE MATERIALIZED VIEW“中”既“改成"即"
=> ”CREATE MATERIALIZED VIEW“中”既“改成"即"

sql-reference/sql-statements/Administration/ADMIN CHECK TABLET.md
fix typo https://github.com/StarRocks/docs.zh-cn/issues/1619
=> fix typo #1619

loading/Flink-connector-starrocks.md
update flink-connector sink.max-retries
=> update flink-connector sink.max-retries

using_starrocks/timezone.md
=> [Community-P3] Modify typos

release_notes/release-1.19.md
colocated join-->colocate join
=> [Community-P3] Modify colocated join to colocate join

using_starrocks/External_table.md
修改一处MySQL版本号，通常大家认为MySQL 5.7的后一个版本为8.0版本。
=> [Community-P3] Modify a MySQL version number

loading/SparkLoad.md
=> [Community-P3] Modified several typography in Spark Load documentation that may affect reading

loading/Flink_cdc_load.md
=> [Community-P3] Fix mysqld script startup command path

loading/Flink-connector-starrocks.md
=> [Community-P3] Fixed a small bug in the description

using_starrocks/Bitmap_index.md
=> [Community-P3] Remove extra quotes

administration/deploy_broker.md
=> [Community-P2] 建议 Broker 节点的部署数量。

quick_start/Deploy.md
=> [Community-P3] Modify the FE process name to StarRocksFE

quick_start/Deploy.md
Added instructions for binding IP in be.conf
=> [Community-P2] Added instructions for binding IP in be.conf

quick_start/Create_table.md
In StarRocks, the database name is case-sensitive, change the database name here to: information_schema
=> [Community-P3] Change the database name to: information_schema

using_starrocks/Using_bitmap.md
=> [Community-P3] Statement is not smooth

using_starrocks/Using_HLL.md
=> [coumunity-P3]  HLL abbreviations problems in Using_HLL.md

using_starrocks/Using_HLL.md, using_starrocks/Using_bitmap.md
=> [coumunity-P3]  One extra dot before the word in_bitmap.md

data_source/External_table.md
=> [coumunity-P3] Update space between Chinese and English problems in External_table.md

data_source/catalog/query_external_data.md
=> [coumunity-P3] Update space between Chinese and English problems in query_external_data.md

data_source/catalog/iceberg_catalog.md
=> [coumunity-P3] Update space between Chinese and English problems in iceberg_catalog.md

data_source/catalog/catalog_overview.md
=> [coumunity-P3] Update space between Chinese and English problems in catalog_overview.md

data_source/catalog/hive_catalog.md
=> [coumunity-P3] Update space between Chinese and English problems in hive_catalog.md 

introduction/what_is_starrocks.md
The abbreviation does not give the full meaning
=> [coumunity-P3] Short for normative problem

using_starrocks/Cost_based_optimizer.md
修改部分是基础统计信息模块，row_count 后接冒号与字段中间多1个空格
=> [Community-P3] 修改部分是基础统计信息模块，row_count 后接冒号与字段中间多1个空格

reference/System_variable.md
=> [coumunity-P3] Update space between Chinese and English problems in System_variable.md

data_source/catalog/default_catalog.md
=> [coumunity-P3] Add space between Chinese and English

data_source/catalog/default_catalog.md
=> [coumunity-P3] Update space between Chinese and English problems in default_catalog.md

sql-reference/sql-functions/string-functions/concat_ws.md, sql-reference/sql-statements/Utility/DESCRIBE.md
=> [coumunity-P3] Update space between Chinese and English problems in  DESCRIBE.md

sql-reference/sql-statements/data-definition/CANCEL ALTER TABLE.md
=> [Community-P1] Create CANCEL ALTER TABLE.md

sql-reference/sql-functions/bitmap-functions/bitmap_union.md
=> [Community-P1] Update bitmap_union.md

sql-reference/sql-functions/bitmap-functions/bitmap_union_count.md
=> [Community-p1] Update bitmap_union_count.md

loading/Flink-connector-starrocks.md
The format built is not OK. so I delete blank line in the code block first.
=> [docs] flink connector code block format

loading/Flink-connector-starrocks.md
=> change some format of flink connector

sql-reference/sql-statements/data-manipulation/SELECT.md
=> [Community-P3] Update SELECT.md

quick_start/Deploy.md
=> [coumunity-P3]  Update  BE download link  in Deploy.md

quick_start/Create_table.md
=>  [coumunity-P3] The expression is defective in Create_table.md

quick_start/Import_and_query.md
Stream load spelling error , should be Stream Load
=>  [coumunity-P3] Incorrect spelling of upper and lower case in Import_and_query.md

administration/Monitor_and_Alert.md
=> [coumunity-P3] Not using exact words in Monitor_and_Alert.md

administration/Monitor_and_Alert.md
=> [coumunity-P3] Update space between Chinese and English problems in Monitor_and_Alert.md

administration/Profiling.md
=> [coumunity-P3] Update space between Chinese and English problems in Profiling.md

administration/Backup_and_restore.md
=> [Community-P3]Update Backup_and_restore.md

administration/Configuration.md
=> [Community-P3]Update Configuration.md

administration/Resource_Group.md
SHOW RESOURCE GROUP group_name；
中文分号，低错
=> [Community-P2]Update Resource_Group.md

administration/Blacklist.md
=> [Community-P2]Update Blacklist.md

data_source/External_table.md, data_source/catalog/hudi_catalog.md
https://github.com/StarRocks/starrocks/pull/6780
=> Update hudi docs

data_source/catalog/hive_catalog.md
Adjust an expression in the text
=> [Community-P3] Adjust an expression in the text

introduction/system_architecture.md
=> [Community-P3]Update system_architecture.md

administration/deploy_with_docker.md
修正缺少的$符号，正确的是 $StarRocks_version
=> [community-p1] Update deploy_with_docker.md

data_source/External_table.md
=> [Community-P3] Remove spaces in datatime field data in insert statement

data_source/External_table.md
=> [Community-P3] Modify a "host" in the document to "hosts"

sql-reference/sql-statements/account-management/CREATE ROLE.md
=> [Community-P3]Modify the format in the create role

sql-reference/sql-statements/account-management/ALTER USER.md
=> [Community-P3]Modify punctuation and format in alter user

administration/Memory_management.md
=> [Community-P1] 修改2.4版本page_cache两处参数默认值

sql-reference/sql-statements/data-manipulation/SHOW BACKUP.md
=> Update SHOW BACKUP.md

data_source/External_table.md
删除常见问题描述中的"不是9931"，这个端口上下文均没有提到，建议删除
=> [Community-P3] Remove "不是 9931" in FAQ description

table_design/Temporary_partition.md
=> [Community-P3] Update Temporary_partition.md

table_design/Data_model.md
删除建表语句中的  “....” 字符，防止复制黏贴后执行出现` ERROR 1064 (HY000): Syntax error in line 1:`
=> [community-p1] Update Data_model.md

sql-reference/sql-statements/data-manipulation/PAUSE ROUTINE LOAD.md
=> [community-P3] 标点符号错误

faq/loading/Routine_load_faq.md
1. 中英文空格优化；
2. 为部分命令增加链接；
3. 将两个英文之间的顿号换成逗号。
=> [community-P3] Routine_load_faq.md 多处优化

loading/Flink_cdc_load.md
=> [Community-P3]Modify the Flink CDC connector download link

sql-reference/sql-statements/data-manipulation/RESUME ROUTINE LOAD.md
=> [community-P3] 修正拼写错误

data_source/External_table.md
=> [Community-P3] Add and change the available model of the current UPDATE operation to "unique key model + primary key model"

loading/SparkLoad.md
=> [Community-P3] Add a period at the end of the sentence in SparkLoad.md

sql-reference/sql-statements/data-types/STRING.md
=> [Community-P3]Update STRING.md

administration/enable_fqdn.md
=> [Community-P2] Modify a description of LEADER

administration/Monitor_and_Alert.md
=> <SPACE> [Community-P3] Add a space between Chinese and English characters

administration/Configuration.md
=> [Community-P3] Add a period at the end of the sentence

administration/Scale_up_down.md
调整两处master为leader。新版本应是计划统一FE角色概念，不再混用Master和Leader，统一调整为Leader。
=> [Community-P3] Adjust the two masters in the document to be the leader

quick_start/Deploy.md
=> [Community-P2] Adjust the FE display information to version 2.4, and modify the character description

administration/Deployment.md
建议删除文档中的关于"下一步"的操作。本文讲述部署FE高可用，正常来说需要在“整个集群”部署完成后再进行建表和导数据操作。
=> [Community-P3] It is recommended to delete the action about "next" in the document

administration/Deployment.md
=> <SPACE> [Community-P3] Add a space between Chinese and English

administration/Build_in_docker.md
修改编译命令'sh /build.sh'为'sh build.sh'。
=> [Community-P1] Modify 'sh /build.sh' to 'sh build.sh'

administration/Build_in_docker.md
=> [Community-P3] Modify the instructions when mounting local storage

administration/Build_in_docker.md
=> [Community-P3] Add 2.3 and 2.4 version docker image name

administration/deploy_with_manager.md
=> [Community-P3] Adjusted two layouts in the FAQ section

using_starrocks/Using_bitmap.md
=> [Community-P3] Add a space between Chinese and English

administration/deploy_with_manager.md
修改Broker的建议安装数。Broker目前建议和BE混布，不太有必要在集群所有节点部署。
=> [Community-P2] Modify the recommended number of installations for Broker

administration/deploy_with_manager.md
=> [Community-P3] Modify the metadata directory name starrocks-meta to meta

administration/deploy_with_manager.md
修改一处Follower FE个数的建议值。目前只建议部署3个Follower FE组成HA。
=> [Community-P2] Modify the recommended value of the number of Followers FE in one place

administration/deploy_with_manager.md
=> [Community-P2] Added several explanations for the Python environment

administration/stargo.md
=> <SPACE> [Community-P3] Remove three extra spaces

using_starrocks/Colocate_join.md
修改标题"删除 Colocation 表"为"删除 Colocation Group"。下文段中的描述不太是说删除表的。
=> [Communtiy-P3] Modify the title "Delete Colocation Table" to "Delete Colocation Group"

using_starrocks/Materialized_view.md
修改文中一处对于'CANCEL REFRESH MATERIALIZED VIEW'命令的描述
=> [Communtiy-P2] Modify the description of the 'CANCEL REFRESH MATERIALIZED VIEW' command in one place in the documentation

sql-reference/sql-statements/Administration/ALTER SYSTEM.md
=>  [Community-P3]Modify the command to view fe status

administration/Cluster_administration.md
在启动FE集群部分增加指定--helper的描述，不然FE集群无法正常启用。
=> [Communtiy-P1] Add the description of the specified "--helper" in the starting FE cluster section

using_starrocks/Using_bitmap.md
修改INT32为INT。通常INT32等价于常用的INT类型，但SR中没有单独提到INT32类型。同时顺手调整了几处标点和多余空格。
=> [Community-P3] Modify INT32 to INT

using_starrocks/Bitmap_index.md
Reverts StarRocks/docs.zh-cn#2856
=> Revert "[Communtiy-P3] Delete PROPERTIES "storage_type" = "column" in the create table statement"

quick_start/Deploy.md
=> Update Deploy.md download link

loading/SparkLoad.md
=>  [coumunity-P3]  Correct Chinese and English commas in SparkLoad.md

administration/Configuration.md
Only for version 2.3 (from 2.3.6).
=> [Doc] Add FE.config enable_pipeline_load_for_insert

TOC.md, sql-reference/sql-functions/scalar-functions/hll_cardinality.md
Signed-off-by: xlfjcg <1937532871@qq.com>
=> Add hll_cardinality.md

data_source/External_table.md
follow https://github.com/StarRocks/starrocks/pull/15606
=> update aliyun oss docs

loading/Loading_intro.md
=> [Community-P3] Modify the upper limit of imported memory to machine memory x90%x90%x30%

loading/Loading_intro.md
=> [Community-P3] Modify the software limit of BE available machine memory to machine memory*90%*90%

administration/Cluster_administration.md
fix update 1.19 to 2.0.x doc error
ADMIN SET FRONTEND CONFIG ("tablet_sched_max_scheduling_tablets" = "0");
ADMIN SET FRONTEND CONFIG ("tablet_sched_max_balancing_tablets" = "0");
change to 
ADMIN SET FRONTEND CONFIG ("max_scheduling_tablets" = "0");
ADMIN SET FRONTEND CONFIG ("max_balancing_tablets" = "0");
=> [community- p1] fix update 1.19 to 2.0.x doc error

administration/k8s_operator_cn.md
=> [Community-P2] Modify the address of the clone code

administration/k8s_operator_cn.md
=> [Community-P3] Adjust the formatting in a document that does not interfere with reading

using_starrocks/Colocate_join.md
调整文中四处"Colocation Join"为"Colocate Join"
=> [Communtiy-P3] Adjust "Colocation Join" in four places in the document to "Colocate Join"

loading/DataX-starrocks-writer.md
=> [Community-P1] Fixed description of DataX import task containing dirty data

table_design/Data_distribution.md
问题描述:`SET GLOBAL enable_tablet_internal_parallel;` 
建议的修改:`SET GLOBAL enable_tablet_internal_parallel=true;`
=> [Community-P2]数据分布-确定分桶数量-参数使用方法描述不明确

loading/Flink-connector-starrocks.md
修改“Stream Load任务状态”为“Stream Load返回值”并调整对应链接（相对路径）
=> [Community-P2] Modify a description and hyperlinks

table_design/Data_model.md
=> [Community-P3] Modify the description of "Import" in the Aggregate Model table "Next" in the documentationUpdate Data_model.md

faq/loading/Flink_connector_faq.md, loading/Flink-connector-starrocks.md
Add doc for `sink.properties.timeout`, and explain the possible problem if it's smaller than the Flink checkpoint interval
=> Add doc for sink.properties.timeout

administration/Monitor_and_Alert.md, administration/Resource_Group.md
=> Update document about resource group

loading/Flink_cdc_load.md
Signed-off-by: hellolilyliuyi <hellolilyliuyi123@163.com>
=> fix broken links

integrations/datadog_support.md, integrations/intro.md, integrations/superset_support.md
#4178 
Add datadog-connector doc
#4179 
Add superset-connector doc
=> [Doc]Add datadog-connector&superset-connector doc

administration/User_privilege.md
172.10.1.10属于公网IP地址，从安全角度讲，资料里面，不应出现公网IP。建议修改为：
A类私网IP：10.0.0.0/8
B类私网IP：172.16.0.0/12
C类私网IP：192.168.0.0/16
=> [Community-P1]Update User_privilege.md

using_starrocks/Bloomfilter_index.md
=> [Community-P2] Add a description to modify the index

sql-reference/sql-statements/data-types/BITMAP.md
bitmap不仅可以作为聚合模型使用，也可以在其他模型下，这个md说明误导了
=> [community-p1] Update BITMAP.md

loading/Flink_cdc_load.md
Signed-off-by: hellolilyliuyi <hellolilyliuyi123@163.com>
=> fix bug in loading from mysql

sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Signed-off-by: hellolilyliuyi <hellolilyliuyi123@163.com>
=> bugfixes in create routine load

sql-reference/sql-statements/Administration/ALTER SYSTEM.md
Signed-off-by: Dejun Xia <xiadejun@starrocks.com>
=> Add doc for alter system create image

sql-reference/sql-statements/data-manipulation/SHOW RESTORE.md
Add the missing field `Progress` in the return.
=> Update SHOW RESTORE.md

sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
Reverts StarRocks/docs.zh-cn#4728
=> Revert "modify examples in create routine load (backport #4716)"

table_design/Data_distribution.md
Reverts StarRocks/docs.zh-cn#4699
=> Revert "[Doc] Batch partition already supports the HOUR granularity"

table_design/Data_distribution.md
(cherry picked from commit 825e58176b1735e431d9725185f46c743f546fb7)
#	table_design/Data_distribution.md
=> Update Data_distribution.md (#4764)

administration/Configuration.md
Change the storage_page_cache_limit configuration item from static to dynamic
=> [Doc] Update Configuration.md

sql-reference/sql-functions/map-functions/map_filter.md, sql-reference/sql-functions/map-functions/transform_keys.md, sql-reference/sql-functions/map-functions/transform_values.md
support map_filter/transform_keys/transform_values
=> [3.0] support map_filter/transform_keys/transform_values

administration/Configuration.md
Reverts StarRocks/docs.zh-cn#4871
=> Revert "Update Configuration.md"

unloading/Spark_connector.md
=> 添加spark connector下载地址

using_starrocks/Using_bitmap.md
修改本地文件导入的命令。原语句写法上应该有点问题，推测作者是想通过一整句命令直接完成数据导入，所以考虑修改为echo生成文件的方式实现。
=> [Community-P1] Commands to modify the import of local files

deployment/environment_configurations.md
should cherry-pick to branch-3.0, branch-2.5, branch-2.4
=> modify max_map_count default value

quick_start/Create_table.md
=> GRANT ALL grammatical fix

sql-reference/sql-statements/data-manipulation/CREATE ROUTINE LOAD.md
The kafka property should be placed in the datasource domain.
=> Update CREATE ROUTINE LOAD.md

release_notes/release-3.0.md
Signed-off-by: wangsimo0 <[wangsimo418@gmail.com](mailto:wangsimo418@gmail.com)>
=> [doc]Update release-3.0.md

release_notes/release-2.3.md
Reverts StarRocks/docs.zh-cn#5845
=> Revert "add 2.3.14 release-2.3.md"

benchmarking/TPC-H_Benchmark.md
=> Update TPC-H Q13

administration/Memory_management.md, using_starrocks/Materialized_view.md
Reverts StarRocks/docs.zh-cn#6163
=> Revert "adjust column width"

faq/Deploy_faq.md, sql-reference/sql-statements/data-manipulation/STREAM LOAD.md
=> [Doc] spelling of PLAIN

sql-reference/sql-statements/data-manipulation/UPDATE.md
=> [Doc] spelling of EXPLAIN

README.md
=> Update version info in README.md

README.md
=> 删除 2.4 README.md

data_source/data_cache.md
1. Use the fileModificationTime to replace origin fileSize
2. Optimize some theoretical explanations
3. Show the default values of BE configurations for data cache.
=> Update data_cache.md to import the file modification time in cache key and specify the default values for data cache configuration.

administration/Configuration.md
=> add unit to four mutable para

administration/privilege_faq.md
=> [doc]Update privilege_faq.md

lychee.toml
This fixes all of the false errors except two
=> ignore example urls

loading/Kafka-connector-starrocks.md
…rker configuration file and start kafka connect
=>  add more description about how to copy the connector to the pugin path

sql-reference/sql-statements/data-definition/ALTER_TABLE.md, sql-reference/sql-statements/data-definition/CREATE_TABLE.md
1. alter table 支持手动 compaction
2. 添加多列时可指定添加的位置
增加了语法和对应示例，同时优化了 alter table 的描述
=> alter table 增加手动 compaction 功能

sql-reference/sql-statements/account-management/GRANT.md, sql-reference/sql-statements/account-management/REVOKE.md
=> update revoke syntax

TOC.md, sql-reference/sql-functions/function-list.md, sql-reference/sql-functions/utility-functions/is_role_in_session.md, sql-reference/sql-statements/account-management/SET_ROLE.md
add this function, supported in 3.1.4 and later
=> 增加函数 is_role_in_session

table_design/expression_partitioning.md
=> Add the supported version for Partitioning based on the column expression in starrocks shared-data mode

release_notes/release-2.5.md
=> add 2.5.14 rn
