benchmarking/SSB_Benchmarking.md

原来文档中没有明确指出create_db_table.sh的路径，导致用户可能找不到，我将准确路径贴了上去

添加性能测试模块create_db_table.sh的路径

---

quick_start/Deploy.md

目前官方文档存在两个删除BE的命令，有的用户以为这两个是一个删除BE的命令，导致出错，不推荐用户使用第二种删除命令，故现在需要删掉

BE出错时的删除命令修改

---

sql-reference/sql-statements/data-definition/DROP TABLE.md

Now the usge of `Drop Table Force` in doc page has some error as below:
The correct usage is this:

Update ForceDropTable Usage

---

sql-reference/sql-statements/data-definition/CREATE TABLE.md

第二点和第五点说法不一致，实际上可以指定多个range分区键的，故在2处将其去掉，以第五处的描述为准

Update CREATE TABLE.md

---

sql-reference/sql-statements/data-definition/CREATE TABLE.md

The size of `DOUBLE` should be 8 bytes not 12 bytes.

Fix: size of DOUBLE should be 8 bytes not 12 bytes

---

quick_start/Import_and_query.md

修复文档中：https://docs.starrocks.com/zh-cn/main/quick_start/Import_and_query 不可用的链接

修复导入和查询章节里404的链接

---

sql-reference/sql-statements/data-types/JSON.md

In 2.2.1 and later version, JSON could be used in unique/primary table.
Related issue: https://github.com/StarRocks/starrocks/issues/6543

support use JSON in unique and primary key

---

administration/Deployment.md

Correct the description of BDBJE, which is a paxos-like protocal, rather than raft-like.

Correct the description of BDBJE

---

loading/RoutineLoad.md

remove ";" after "\G"
```
SHOW ROUTINE LOAD\G;
ERROR: No query specified
```

remove ";" after "\G"

---

using_starrocks/Using_HLL.md

将 “说明” 和 正文内容 放在两行，否则阅读时语句不通顺，容易引起歧义

[Community-P3] The prompt and body are placed on different lines

---

using_starrocks/Using_HLL.md

[Community-P3] Failed to write data due to wrong table name

---

quick_start/Deploy.md

基于社区使用高版本JDK出现过多次稳定性问题，在文档中给出推荐JDK版本为1.8

[Community-P3] Added in the documentation, JDK1.8 is recommended

---

administration/Configuration.md

`es_state_sync_interval_second` 也用来控制StarRocks外部表元信息周期性同步的时间间隔

完善es_state_sync_interval_second的解释

---

using_starrocks/Using_bitmap.md

[Community-P3] There is one more point in front of BITMAP

---

data_source/catalog/hive_catalog.md

Hive中INT和INTEGER通常认为是一种类型的两种写法，用INT/INTEGER更合适一些

[Community-P3] Modify "INT、INTEGER" to "INT/INTEGER"

---

data_source/External_table.md

删除ES外表文档中的"表 1 ：支持的谓词下推列表"，这一句描述略显缀余。

[Community-P3] Delete a description that is suspected to be redundant in the document

---

sql-reference/sql-statements/data-manipulation/ROUTINE LOAD.md

[community-P3] MarkDown 格式优化

---

using_starrocks/Bitmap_index.md

删除建表语句中的PROPERTIES ("storage_type" = "column")。该属性添加后虽然建表不报错，但是StarRocks中实际并不支持手动配置存储方式为行存列存，默认即为列存，此外也没有其他地方介绍过这个属性，为避免引起读者误解，建议删除。文档中其他发现有该参数的地方，稍后也逐个提PR。

[Communtiy-P3] Delete PROPERTIES "storage_type" = "column" in the create table statement

---

administration/Metadata_recovery.md

Steps of cleaning up mate/* are missing from the page of restoring metadata documents
https://github.com/StarRocks/starrocks/issues/13508

[Docs] fix Steps of cleaning up mate/* are missing from the page of restoring metadata documents

---

unloading/Spark_connector.md

Since StarRocks 2.2, the allowed minimum batch size is 4096, and when setting a batch size smaller than 4096, the StarRocks will reset it to 4096. To make the default value meaningful for all versions of StarRocks, we also change the default value of spark connector to 4096.

Change the default value of starrocks.batch.size

---

reference/System_variable.md

`SET_VAR` 为 MySQL 在 8.0 之后的版本引入的 feature: [Variable-Setting Hint Syntax](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-set-var)。
用户如果使用 8.0 以下客户端连接(包括最新版本 MariaDB)，该提示无法生效，且没有任何报错信息，产生不符合预期的行为。
建议增加相关标注，避免出现误解。

[community-P1] SET_VAR 提示在 MySQL 8.0 以下版本无效

---

using_starrocks/Lateral_join.md

删除开启CBO优化器的操作。2.4版本的系统变量中已经没有enable_cbo这一项，默认集成且启用了CBO优化器，已无法手动关闭，这步操作已没有意义。

[Community-P2] Delete the operation of opening the CBO optimizer

---

loading/DataX-starrocks-writer.md

Stream Load任务无法通过show load语句查看，调整为根据Stream Load返回值查看任务情况。

[Community-P1] Corrected the way to view the DataX stream load task

---

loading/Flink_cdc_load.md

修改文档示例中的JDK版本为OpenJDK 8。在官网文档中显示Oracle JDK 1.8版本可能是不妥的，Oracle在JDK 1.8.0_211及之后版本将协议从BCL修改为可按照商业用途收费的OTN协议，后续大版本商用仍有风险，直至JDK 17版本(NFTC许可) 才再次可免费商用。

[Community-P0_maybe] Modify the JDK version in the documentation example to OpenJDK 8

---

sql-reference/sql-statements/data-manipulation/SHOW DYNAMIC PARTITION TABLES.md

执行语句查询的结果与语句描述不符，查询的结果中有动态分区属性为false的分区表，即查询的结果为所有设置过动态分区属性的表，无论是现在的动态属性分区是否开启。

[Communtiy-P1] SHOW DYNAMIC PARTITION TABLES 执行结果与文档描述不符

---

.github/workflows/markdownlint.yml
.lycheeignore
lychee.toml

Adds a link checker to the linting workflow. For the moment this is checking only Markdown links to local Markdown files. Once we have all of those fixed we can expand to external links.

check links
